theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: after-hero
  posts:
    index:
      layout: grid
  logo:
    line: CEPIR
    footer: "/assets/images/logo-white.svg"
