theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: hero-start
  summary:
    position: hero
  posts:
    index:
      layout: grid
  logo:
    line: CEPIR
    footer: "/assets/images/logo-white.svg"
    footer_line: Cas d’Étude Pour un Immersif Responsable
